export type CategoryIconKey = "Bot" | "MessageSquare" | "ShoppingCart" | "Zap" | "BarChart3" | "BookOpen" | "CreditCard" | "Users" | "Settings" | "Puzzle"

export interface Article {
  slug: string
  title: string
  category: string
  content: string
}

export interface Category {
  iconKey: CategoryIconKey
  title: string
  articles: Article[]
}

const gs: Article[] = [
  { slug: "connecting-shopify-store", title: "Connecting your Shopify store", category: "Getting Started", content: `## Connecting your Shopify store\n\nReplyma integrates with Shopify in one click via the Shopify App Store.\n\n### Steps\n\n1. Go to **Settings → Integrations** in your Replyma dashboard.\n2. Click **Connect Shopify**.\n3. You will be redirected to Shopify to approve the app permissions.\n4. Once approved, your store data (orders, customers, products) syncs automatically.\n\n### What syncs?\n\n- **Orders** — status, tracking info, line items, refund history.\n- **Customers** — email, name, total spent, order count.\n- **Products** — titles and variants (used by the AI for product questions).\n\nSync happens in real-time via Shopify webhooks. Historical data loads within a few minutes.\n\n### Permissions required\n\n- Read orders, customers, and products.\n- Write access for refunds and order cancellations (Shopify actions from inbox).\n\nIf you have issues, make sure your Shopify plan supports third-party apps.` },
  { slug: "setting-up-ai-agent", title: "Setting up the AI agent", category: "Getting Started", content: `## Setting up the AI agent\n\nThe AI agent is the core of Replyma. It reads customer messages, understands intent, and crafts accurate replies.\n\n### Quick setup\n\n1. Go to **AI → Settings** in the dashboard.\n2. Set your **AI tone** (friendly, professional, casual, etc.).\n3. Toggle **Auto-reply** on to let the AI respond automatically.\n4. Add **escalation keywords** — words that always route to a human (e.g., "lawsuit", "manager").\n\n### How it works\n\nWhen a customer sends a message:\n1. Replyma detects sentiment (positive, neutral, negative, angry).\n2. It classifies the intent (order status, return, billing, etc.).\n3. It searches your knowledge base using RAG (vector similarity).\n4. It fetches relevant Shopify order data.\n5. It generates a reply using all this context.\n\nIf the AI is unsure or the query needs human judgment, it escalates automatically.\n\n### Test before going live\n\nUse the **Test Reply** box on the AI settings page. Type a sample customer message and see exactly what the AI would respond.` },
  { slug: "uploading-return-policy", title: "Uploading your return policy", category: "Getting Started", content: `## Uploading your return policy\n\nThe AI references your return policy in every relevant reply. This ensures accurate, consistent answers about returns, exchanges, and refunds.\n\n### How to upload\n\n1. Go to **AI → Settings**.\n2. Find the **Return Policy / Company Knowledge** text area.\n3. Paste your full return policy text.\n4. Click **Save**.\n\nYou can also add general company knowledge here — shipping times, warranty info, sizing guides, etc.\n\n### Tips for best results\n\n- Be specific: "Returns accepted within 30 days of delivery" is better than "We accept returns."\n- Include exceptions: "Final sale items cannot be returned."\n- Add your refund method: "Refunds are issued to the original payment method within 5–7 business days."\n- Mention exchange policies separately.\n\nThe AI will quote this text when answering return questions. The more detailed your policy, the more accurate the replies.` },
  { slug: "inviting-team-members", title: "Inviting team members", category: "Getting Started", content: `## Inviting team members\n\nAdd agents, admins, and viewers to your Replyma workspace.\n\n### How to invite\n\n1. Go to **Team** in the sidebar.\n2. Click **Invite Member**.\n3. Enter their email, name, and select a role.\n4. They will receive an email with a link to set their password and join.\n\n### Roles\n\n- **Admin** — full access. Can manage billing, settings, and team members.\n- **Agent** — can view and respond to tickets, use macros, and see analytics.\n- **Viewer** — read-only access to the inbox and analytics.\n\n### Seat limits\n\nYour plan determines how many agent seats you have:\n- Free: 1 seat\n- Starter: 2 seats\n- Growth: 5 seats\n- Scale: unlimited seats\n\nUpgrade your plan in **Billing** if you need more seats.` },
]

const ch: Article[] = [
  { slug: "connecting-email", title: "Connecting email addresses", category: "Channels & Inbox", content: `## Connecting email addresses\n\nReplyma supports two email modes: **Managed** and **Forwarding**.\n\n### Managed mode (recommended)\n\nReplyma gives you a dedicated inbound address like \`support-abc12@email.replyma.com\`. Share this address with customers or set it as your support email.\n\n1. Go to **Channels → Email**.\n2. Select **Managed mode**.\n3. Copy your unique inbound email address.\n4. Set it as your "Reply-To" or support contact.\n\n### Forwarding mode\n\nKeep your existing email (e.g., support@yourstore.com) and forward it to Replyma.\n\n1. Go to **Channels → Email**.\n2. Select **Forwarding mode**.\n3. Enter your sending email address.\n4. Set up auto-forwarding in your email provider to forward incoming mail to your Replyma inbound address.\n5. Click **Verify Forwarding** to confirm.\n\n### Custom domain (optional)\n\nFor branded emails, verify your own domain:\n1. Go to **Channels → Email → Verify Domain**.\n2. Add the DNS records shown (DKIM + SPF).\n3. Wait for verification (usually 5–30 minutes).\n\nOnce verified, replies come from your domain instead of replyma.com.` },
  { slug: "email-forwarding-setup", title: "Email forwarding setup", category: "Channels & Inbox", content: `## Email forwarding setup\n\nForwarding lets you keep your existing support@yourstore.com address while routing everything through Replyma.\n\n### Gmail / Google Workspace\n\n1. Open Gmail → Settings → Forwarding.\n2. Add your Replyma inbound address.\n3. Confirm the verification email.\n4. Set to "Forward a copy" and keep the original.\n\n### Outlook / Microsoft 365\n\n1. Go to Settings → Mail → Forwarding.\n2. Enable forwarding and enter your Replyma inbound address.\n3. Optionally keep a copy in Outlook.\n\n### Custom providers\n\nMost email providers support auto-forwarding. Look for "Forwarding", "Redirect", or "Rules" in your email settings. Create a rule that forwards all incoming mail to your Replyma address.\n\n### Verifying\n\nAfter setting up forwarding:\n1. Go to **Channels → Email** in Replyma.\n2. Click **Verify Forwarding**.\n3. Replyma sends a test email. If forwarding is working, verification completes automatically.\n\nIf verification fails, double-check your forwarding rules and try again.` },
  { slug: "live-chat-widget", title: "Live Chat widget installation", category: "Channels & Inbox", content: `## Live Chat widget installation\n\nEmbed the Replyma chat widget on your website to offer instant AI-powered support.\n\n### Installation\n\n1. Go to **Channels → Live Chat** in the dashboard.\n2. Copy the embed code snippet.\n3. Paste it before the closing \`</body>\` tag on your website.\n\n### Shopify\n\nFor Shopify stores:\n1. Go to **Online Store → Themes → Edit Code**.\n2. Open \`theme.liquid\`.\n3. Paste the embed code before \`</body>\`.\n4. Save.\n\n### WordPress / WooCommerce\n\n1. Go to **Appearance → Theme Editor** or use a plugin like "Insert Headers and Footers".\n2. Paste the embed code in the footer section.\n\n### Customization\n\nThe widget inherits your accent color from settings. You can customize:\n- Widget color\n- Greeting message\n- Proactive trigger delay (seconds before the widget nudges the visitor)\n- Quick reply suggestions\n\n### How it works\n\nWhen a visitor sends a message through the widget:\n1. A ticket is created in your inbox.\n2. The AI processes it and responds in real-time.\n3. If escalated, your team sees it immediately with a notification.\n\nMessages appear in both the widget and your Replyma inbox.` },
  { slug: "inbox-keyboard-shortcuts", title: "Inbox keyboard shortcuts", category: "Channels & Inbox", content: `## Inbox keyboard shortcuts\n\nNavigate your inbox faster with keyboard shortcuts.\n\n| Shortcut | Action |\n|----------|--------|\n| \`j\` / \`k\` | Move up/down in ticket list |\n| \`Enter\` | Open selected ticket |\n| \`Escape\` | Close ticket / deselect |\n| \`Cmd+K\` | Open command palette |\n| \`r\` | Reply to current ticket |\n| \`n\` | Add internal note |\n| \`e\` | Close / resolve ticket |\n| \`s\` | Snooze ticket |\n| \`a\` | Assign ticket |\n| \`?\` | Show shortcuts help |\n\n### Command palette\n\nPress \`Cmd+K\` (or \`Ctrl+K\` on Windows) to open the command palette. From there you can:\n- Search tickets by customer name or email\n- Jump to any page in the dashboard\n- Quick-assign tickets\n- Apply macros\n\n### Bulk actions\n\nSelect multiple tickets with checkboxes, then use the bulk action bar to close, assign, or tag them all at once.` },
]

const sh: Article[] = [
  { slug: "one-click-refunds", title: "One-click refunds from inbox", category: "Shopify & WooCommerce", content: `## One-click refunds from inbox\n\nProcess Shopify refunds directly from the ticket sidebar without leaving Replyma.\n\n### How to refund\n\n1. Open a ticket from a customer.\n2. In the customer sidebar, find the **Shopify Orders** section.\n3. Click the order you want to refund.\n4. Click **Refund** and optionally enter a partial amount and reason.\n5. Confirm. The refund is processed in Shopify immediately.\n\n### What happens after\n\n- A system message is added to the ticket: "Order #1234 refunded ($XX.XX) by Agent Name."\n- An audit log entry is created.\n- The customer receives Shopify's standard refund notification email.\n- Revenue attribution is updated in analytics.\n\n### Partial vs full refunds\n\n- Leave the amount empty for a full refund.\n- Enter a specific amount for a partial refund.\n\n### Permissions\n\nRefund access requires the Shopify integration to be connected and the agent to have ADMIN or AGENT role.` },
  { slug: "order-lookup", title: "Order lookup and editing", category: "Shopify & WooCommerce", content: `## Order lookup and editing\n\nWhen the AI detects an order-related question, it automatically fetches the customer's Shopify orders.\n\n### Automatic lookup\n\nThe AI matches the customer's email against your Shopify store. If orders are found, the AI includes order details (status, tracking, items) in its reply.\n\n### Manual lookup\n\nAgents can view orders in the customer sidebar:\n1. Open any ticket.\n2. Click the customer sidebar (right panel).\n3. The **Orders** section shows recent orders with status, total, tracking.\n\n### Editing shipping address\n\nFrom the ticket sidebar, agents can update the shipping address on unfulfilled orders:\n1. Click the order.\n2. Click **Update Address**.\n3. Edit the fields and save.\n\nThe update is applied in Shopify immediately.` },
  { slug: "woocommerce-setup", title: "WooCommerce REST API setup", category: "Shopify & WooCommerce", content: `## WooCommerce REST API setup\n\nConnect your WooCommerce store to sync orders and customer data.\n\n### Prerequisites\n\n- WooCommerce 5.0 or later.\n- WordPress REST API enabled (enabled by default).\n- An SSL certificate on your store (required for API authentication).\n\n### Steps\n\n1. In your WordPress admin, go to **WooCommerce → Settings → Advanced → REST API**.\n2. Click **Add Key**.\n3. Set description to "Replyma", user to your admin account, permissions to **Read/Write**.\n4. Click **Generate API Key**.\n5. Copy the **Consumer Key** and **Consumer Secret**.\n6. In Replyma, go to **Settings → Integrations**.\n7. Click **WooCommerce → Connect**.\n8. Enter your store URL, consumer key, and consumer secret.\n9. Click **Save**.\n\nReplyma will verify the connection and start syncing orders and customers.\n\n### What syncs\n\n- Orders (status, items, totals, tracking).\n- Customers (email, name, order history).\n\nSync happens on-demand when a ticket is opened for a customer.` },
  { slug: "fulfillment-edge-cases", title: "Handling fulfillment edge cases", category: "Shopify & WooCommerce", content: `## Handling fulfillment edge cases\n\nTips for common order scenarios the AI handles.\n\n### Split shipments\n\nIf an order has multiple fulfillments, the AI shows all tracking numbers. The customer gets accurate info even for partially shipped orders.\n\n### Pre-orders\n\nFor unfulfilled orders, the AI explains the order is confirmed and being prepared. It won't fabricate tracking numbers.\n\n### Cancelled orders\n\nAgents can cancel orders directly from the ticket sidebar. The AI then knows the order is cancelled and responds accordingly.\n\n### Out of stock after purchase\n\nIf a customer asks about an order and the items are out of stock, the AI escalates to a human agent since this requires a manual decision (refund, substitute, or wait).\n\n### International orders\n\nTracking links work for all major carriers. The AI includes the carrier name and tracking URL in its response.` },
]

const au: Article[] = [
  { slug: "building-first-rule", title: "Building your first rule", category: "Automation & Rules", content: `## Building your first rule\n\nRules automate repetitive tasks. When conditions are met, actions execute automatically.\n\n### Creating a rule\n\n1. Go to **Rules** in the sidebar.\n2. Click **New Rule**.\n3. Give it a name (e.g., "Auto-tag VIP customers").\n4. Add conditions (e.g., Customer LTV > $500).\n5. Add actions (e.g., Add tag "vip", Set priority "HIGH").\n6. Save and enable.\n\n### Condition types\n\n- **Channel** — email, live chat.\n- **Message contains** — keyword matching.\n- **Customer LTV** — greater than, less than.\n- **Priority** — equals, not equals.\n- **Status** — ticket status matching.\n\n### Action types\n\n- **Assign agent** — route to a specific team member.\n- **Set priority** — change ticket priority.\n- **Add tag** — auto-tag for organization.\n- **Send auto-reply** — respond with a template.\n- **Escalate** — immediately route to human.\n\n### Rule priority\n\nRules are evaluated in priority order (highest first). The first matching rule's actions are executed. Lower-priority rules are skipped.` },
  { slug: "macro-templates", title: "Macro templates library", category: "Automation & Rules", content: `## Macro templates library\n\nMacros are pre-written responses that agents can insert with one click.\n\n### Creating a macro\n\n1. Go to **Macros** in the sidebar.\n2. Click **New Macro**.\n3. Enter a name and the response body.\n4. Use variables like \`{{customer_name}}\`, \`{{order_id}}\`, \`{{tracking_number}}\`.\n5. Save.\n\n### Using macros\n\nWhen replying to a ticket:\n1. Click the macros icon in the reply toolbar.\n2. Search or browse macros.\n3. Click to insert. Variables are replaced with real data.\n\n### Recommended starter macros\n\n- **Order status** — "Hi {{customer_name}}, your order {{order_id}} is currently {{order_status}}."\n- **Refund confirmation** — "Your refund of {{refund_amount}} has been processed."\n- **Shipping delay** — "We're sorry for the delay. Your order is expected to ship by {{restock_date}}."\n- **Return instructions** — "To start a return, please visit [your return portal link]."\n\n### Variables\n\nAvailable variables: \`customer_name\`, \`order_id\`, \`order_status\`, \`tracking_number\`, \`product_name\`, \`refund_amount\`, \`store_name\`, \`restock_date\`.` },
  { slug: "saved-replies-best-practices", title: "Saved replies best practices", category: "Automation & Rules", content: `## Saved replies best practices\n\n### Keep them short\n\nThe best macros are 2–3 sentences. Long responses feel impersonal.\n\n### Use variables\n\nAlways use \`{{customer_name}}\` to personalize. "Hi Sarah" is better than "Hi there."\n\n### Organize by category\n\nName macros clearly: "Return - Standard", "Return - International", "Shipping - Delay". This makes them easy to find.\n\n### Review monthly\n\nCheck which macros agents use most. Archive unused ones. Update outdated ones.\n\n### Combine with the AI\n\nThe AI can apply macros automatically through rules. Set up a rule like:\n- Condition: Intent = "order-status"\n- Action: Apply macro "Order Status Response"\n\nThis handles routine questions without any human involvement.` },
  { slug: "escalation-rules", title: "Escalation rule examples", category: "Automation & Rules", content: `## Escalation rule examples\n\nEscalation rules ensure sensitive tickets reach a human quickly.\n\n### Example 1: Angry customer\n\n- **Condition:** Sentiment = "ANGRY"\n- **Action:** Set priority "URGENT", Assign to senior agent, Escalate\n\n### Example 2: Legal keywords\n\n- **Condition:** Message contains "lawyer" OR "legal" OR "sue"\n- **Action:** Escalate immediately, Add tag "legal-review"\n\n### Example 3: High-value customer\n\n- **Condition:** Customer LTV > $1,000\n- **Action:** Set priority "HIGH", Assign to VIP team\n\n### Example 4: Refund over $100\n\nThe AI automatically escalates refund requests over $100 (built-in behavior). You can adjust this threshold by adding specific rules.\n\n### Example 5: Repeated contact\n\n- **Condition:** Customer has > 3 open tickets\n- **Action:** Add tag "frequent-contact", Assign to account manager\n\n### Tips\n\n- Set escalation rules at high priority so they fire before auto-reply rules.\n- Combine with Pusher notifications so agents see escalations in real-time.` },
]

const an: Article[] = [
  { slug: "ai-resolution-rate", title: "Understanding AI resolution rate", category: "Analytics & Reports", content: `## Understanding AI resolution rate\n\nThe AI resolution rate shows the percentage of tickets the AI resolved without human intervention.\n\n### How it's calculated\n\n\`AI Resolution Rate = (Tickets with status AI_REPLIED / Total tickets) × 100\`\n\nA ticket counts as "AI resolved" if the customer's issue was addressed by the AI and no human agent needed to intervene.\n\n### What's a good rate?\n\n- **50–60%** — Good for new setups.\n- **70–80%** — Strong. Your knowledge base and policies are well-configured.\n- **80%+** — Excellent. Most routine questions are handled automatically.\n\n### How to improve\n\n1. **Add more knowledge base articles** — cover common questions.\n2. **Upload detailed policies** — returns, shipping, warranty.\n3. **Connect Shopify** — order data helps the AI answer WISMO questions.\n4. **Review escalated tickets** — look for patterns the AI could handle with better data.\n5. **Refine escalation keywords** — remove overly broad keywords that cause unnecessary escalations.` },
  { slug: "exporting-csv", title: "Exporting reports as CSV", category: "Analytics & Reports", content: `## Exporting reports as CSV\n\nExport your ticket and customer data for analysis in Excel, Google Sheets, or BI tools.\n\n### Exporting tickets\n\n1. Go to **Settings → General**.\n2. Scroll to the **Export** section.\n3. Click **Export Tickets**.\n4. A CSV file downloads with all ticket data (ID, status, channel, customer email, timestamps, tags, priority, sentiment, intent).\n\n### Exporting customers\n\n1. Same settings page.\n2. Click **Export Customers**.\n3. CSV includes email, name, ticket count, LTV, order count, tags.\n\n### Tips\n\n- Exports include all time data (no date range filter yet — filter in your spreadsheet).\n- Large exports may take a few seconds.\n- Admin role is required for exports.` },
  { slug: "csat-configuration", title: "CSAT survey configuration", category: "Analytics & Reports", content: `## CSAT survey configuration\n\nCustomer satisfaction surveys are sent automatically after ticket resolution.\n\n### Configuration\n\n1. Go to **Settings → CSAT**.\n2. Toggle **Enable CSAT surveys**.\n3. Choose **timing**: immediately, 1 hour, or 24 hours after close.\n4. Choose **scale**: 3-point (Great/OK/Poor) or 5-point (1–5 stars).\n5. Customize the survey **message**.\n6. Optionally enable a **follow-up message** for low ratings.\n7. Save.\n\n### How it works\n\nWhen a ticket is closed:\n1. A survey email is sent to the customer after the configured delay.\n2. The customer clicks a rating.\n3. The rating is recorded and visible on the ticket and in analytics.\n\n### Viewing results\n\n- **Per ticket**: The CSAT rating appears on the ticket in the inbox.\n- **Dashboard**: Go to **Analytics** and check the CSAT section for average score, response rate, and trends.\n- **Per customer**: Customer profiles show their CSAT history.` },
]

const kb: Article[] = [
  { slug: "writing-ai-friendly-policies", title: "Writing policy documents the AI understands", category: "Knowledge Base & AI", content: `## Writing policy documents the AI understands\n\nThe AI reads your knowledge base articles using RAG (Retrieval-Augmented Generation). Here's how to write articles it can use effectively.\n\n### Structure\n\n- **One topic per article**. "Return Policy" and "Shipping Policy" should be separate articles.\n- **Use clear headings** for each section.\n- **Be specific**. "Returns within 30 days" is better than "We have a generous return policy."\n\n### Content tips\n\n- Write in Q&A format when possible: "Q: How long do refunds take? A: 5–7 business days."\n- Include exact numbers, timeframes, and policies.\n- Cover edge cases: international orders, sale items, gift cards.\n- Update articles when policies change.\n\n### What the AI does with your articles\n\n1. When an article is published, Replyma generates a vector embedding.\n2. When a customer asks a question, the AI searches your articles by semantic similarity.\n3. The most relevant articles are included in the AI's context.\n4. The AI references the content in its reply, ensuring accurate answers.\n\n### Publishing\n\nArticles must be published (synced to AI) to be searchable. Draft articles are not used by the AI.` },
  { slug: "rag-retrieval-explained", title: "RAG retrieval explained", category: "Knowledge Base & AI", content: `## RAG retrieval explained\n\nRAG (Retrieval-Augmented Generation) is how Replyma's AI finds relevant information to answer customer questions.\n\n### How it works\n\n1. **Embed**: When you publish a help article, Replyma converts it to a 1024-dimensional vector using Amazon Titan Embed v2.\n2. **Store**: The vector is stored in PostgreSQL using pgvector.\n3. **Search**: When a customer sends a message, the message is also embedded.\n4. **Match**: Replyma finds the top 3 articles with the highest cosine similarity.\n5. **Generate**: The matched articles are included in the AI prompt as context.\n6. **Reply**: The AI generates a response using the retrieved context.\n\n### Why RAG?\n\nWithout RAG, the AI would only know generic information. With RAG, it knows your specific policies, products, and procedures.\n\n### Accuracy\n\nThe AI is instructed to ONLY answer using the retrieved context. It won't make up information. If no relevant articles are found, it will escalate to a human agent.\n\n### Re-indexing\n\nIf you update article content, re-publish it to update the embedding. You can also use the "Re-index All" button on the AI page to regenerate all embeddings at once.` },
  { slug: "testing-ai-accuracy", title: "Testing AI accuracy", category: "Knowledge Base & AI", content: `## Testing AI accuracy\n\nBefore going live, test how the AI responds to common questions.\n\n### Using the test tool\n\n1. Go to **AI → Settings**.\n2. Find the **Test AI Reply** section.\n3. Type a sample customer message.\n4. Click **Test**.\n5. See the AI's response, detected intent, and sentiment.\n\n### What to test\n\n- "Where is my order?" → Should trigger order status lookup.\n- "I want to return this" → Should reference your return policy.\n- "Your product broke" → Should show empathetic response and escalate if needed.\n- "Can I get a refund?" → Should explain your refund process.\n- "I want to speak to a manager" → Should escalate.\n\n### Improving accuracy\n\n1. If the AI gives a wrong answer, check if you have a knowledge base article covering that topic.\n2. If the article exists but the AI doesn't use it, make sure it's published and the title is clear.\n3. Add more specific content for common questions.\n4. Review the AI tone setting — "professional" may be too formal for casual stores.` },
]

// ─── Billing & Account ────────────────────────────

const ba: Article[] = [
  { slug: "plans-and-pricing", title: "Plans and pricing explained", category: "Billing & Account", content: `## Plans and pricing explained\n\nReplyma offers four plans to match your support volume.\n\n### Free plan\n\n- 1 agent seat\n- 25 AI resolutions per month\n- Email + Live Chat\n- Basic inbox\n\n### Starter — $49/mo\n\n- 2 agent seats\n- 500 AI resolutions per month\n- Shopify integration\n- Basic analytics\n\n### Growth — $99/mo\n\n- 5 agent seats\n- 2,000 AI resolutions per month\n- All integrations (Klaviyo, Recharge, etc.)\n- Advanced analytics, macros, rules\n- Knowledge base with RAG\n\n### Scale — $199/mo\n\n- Unlimited seats\n- 10,000 AI resolutions per month\n- Custom AI training\n- SLA guarantee\n- Dedicated onboarding\n\n### Annual billing\n\nSave ~20% by paying annually. Switch between monthly and annual in **Billing**.\n\n### What counts as an AI resolution?\n\nA ticket where the AI responded and the customer did not need to follow up with a human agent. Escalated tickets do not count against your AI resolution limit.` },
  { slug: "upgrading-your-plan", title: "Upgrading your plan", category: "Billing & Account", content: `## Upgrading your plan\n\n### How to upgrade\n\n1. Go to **Billing** in the sidebar.\n2. Click **Upgrade** on the plan you want.\n3. You will be redirected to Stripe Checkout to enter payment details.\n4. After payment, your plan is upgraded immediately.\n\n### What happens when you upgrade\n\n- Your AI resolution limit increases instantly.\n- Additional agent seats become available immediately.\n- You get access to features included in the new plan.\n- Billing is prorated — you only pay the difference for the remaining billing period.\n\n### Managing your subscription\n\nClick **Manage Subscription** in Billing to open the Stripe Customer Portal. From there you can:\n- Update payment method\n- View and download invoices\n- Switch between monthly and annual billing\n- Cancel your subscription\n\n### Cancellation\n\nClick **Cancel Subscription** in Billing. Your workspace will downgrade to the Free plan at the end of the current billing period. All your data is preserved.` },
  { slug: "api-keys", title: "Creating and using API keys", category: "Billing & Account", content: `## Creating and using API keys\n\nAPI keys let external services authenticate with the Replyma API.\n\n### Creating a key\n\n1. Go to **Settings → API Keys**.\n2. Click **Create Key**.\n3. Enter a descriptive name (e.g., "Zapier integration").\n4. The key is shown **once** — copy it immediately.\n5. Store it securely. You cannot retrieve it later.\n\n### Using a key\n\nInclude the key in every API request:\n\n- **Header**: \`x-api-key: rk_your_key_here\`\n- **Or**: \`Authorization: ApiKey rk_your_key_here\`\n\n### Example\n\n\`curl https://api.replyma.com/api/v1/tickets -H "x-api-key: rk_abc123..."\`\n\nThe key gives ADMIN-level access scoped to your workspace. All endpoints under \`/api/v1/\` accept API key auth.\n\n### Revoking a key\n\nGo to **Settings → API Keys**, find the key, and click **Revoke**. The key stops working immediately.\n\n### Security\n\n- Keys are hashed with SHA-256 before storage. We never store the raw key.\n- Set an expiry date when creating the key if you want it to auto-expire.\n- Rotate keys regularly as a best practice.` },
  { slug: "account-settings", title: "Account settings and password", category: "Billing & Account", content: `## Account settings and password\n\n### Updating your profile\n\n1. Go to **Settings → Account**.\n2. Change your display name.\n3. Click **Save**.\n\nYour name appears in ticket replies and team views.\n\n### Changing your password\n\n1. Go to **Settings → Account**.\n2. Scroll to the **Password** section.\n3. Enter your current password.\n4. Enter a new password (minimum 8 characters).\n5. Confirm the new password.\n6. Click **Change Password**.\n\nAll existing sessions are invalidated — you will need to log in again on other devices.\n\n### Two-factor authentication\n\nReplyma uses email-based OTP for login verification. Every time you sign in, a 6-digit code is sent to your email. This code expires in 5 minutes.\n\n### Deleting your account\n\nContact support@replyma.com to request account deletion. All workspace data will be permanently removed.` },
]

// ─── Team & Permissions ──────────────────────────

const tm: Article[] = [
  { slug: "team-roles-permissions", title: "Team roles and permissions", category: "Team & Permissions", content: `## Team roles and permissions\n\nReplyma has three roles with different access levels.\n\n### Admin\n\n- Full access to everything\n- Manage team members (invite, remove, change roles)\n- Manage billing and subscription\n- Configure all settings (channels, integrations, AI, webhooks)\n- Access audit log\n- Export data\n\n### Agent\n\n- View and respond to tickets\n- Use macros and saved replies\n- View customer profiles\n- View analytics (read-only)\n- Cannot manage team, billing, or settings\n\n### Viewer\n\n- Read-only access to the inbox\n- View analytics\n- Cannot respond to tickets or change anything\n\n### Changing roles\n\nAdmins can change any member's role:\n1. Go to **Team**.\n2. Click the member's row.\n3. Select a new role from the dropdown.\n4. Changes take effect immediately.` },
  { slug: "accepting-team-invite", title: "Accepting a team invite", category: "Team & Permissions", content: `## Accepting a team invite\n\nWhen an admin invites you, you receive an email with a link.\n\n### Steps\n\n1. Open the invite email from Replyma.\n2. Click **Accept Invitation**.\n3. Set your password (minimum 8 characters).\n4. Optionally update your display name.\n5. You are now logged in and can access the workspace.\n\n### Troubleshooting\n\n- **Link expired?** Ask the admin to send a new invite from the Team page.\n- **Already have an account?** Each invite creates a user in that specific workspace. If you are on multiple workspaces, you can switch between them.\n- **Didn't receive the email?** Check your spam folder. The email comes from support@replyma.com.` },
  { slug: "managing-online-status", title: "Managing online status", category: "Team & Permissions", content: `## Managing online status\n\nYour status is visible to the team and affects ticket routing.\n\n### Status types\n\n- **Online** — You are active and available for ticket assignment.\n- **Away** — You are temporarily unavailable. New tickets may still be assigned to you.\n- **Offline** — You are not working. No new tickets will be routed to you.\n\n### How it works\n\n- Status is set to **Online** when you log in.\n- Status is set to **Offline** when you log out.\n- The round-robin assignment only routes to **Online** or **Away** agents.\n- Team page shows real-time status for all members via Pusher.` },
]

// ─── Advanced Features ───────────────────────────

const af: Article[] = [
  { slug: "visual-flow-builder", title: "Visual flow builder", category: "Advanced Features", content: `## Visual flow builder\n\nFlows are multi-step automations triggered by events.\n\n### Creating a flow\n\n1. Go to **Flows** in the sidebar.\n2. Click **New Flow**.\n3. Choose a trigger (e.g., "New ticket created").\n4. Add condition nodes (e.g., "If priority is HIGH").\n5. Add action nodes (e.g., "Assign to VIP team", "Send message").\n6. Connect the nodes with edges.\n7. Save and enable.\n\n### Trigger types\n\n- **New ticket created** — fires when any ticket is created\n- **Tag added** — fires when a specific tag is applied\n- **Status changed** — fires on status transitions\n- **Message received** — fires on new customer messages\n\n### Action types\n\n- **Send message** — auto-reply to the customer\n- **Assign agent** — route to a specific agent\n- **Add tag** — apply a tag\n- **Escalate** — escalate to human\n- **Send webhook** — POST to an external URL\n\n### Condition types\n\n- Check customer LTV, sentiment, channel, priority, or tags\n- Conditions branch the flow into "true" and "false" paths\n\n### Flow stats\n\nEach flow tracks execution count, success rate, and node hit maps.` },
  { slug: "customer-segments", title: "Customer segments", category: "Advanced Features", content: `## Customer segments\n\nSegments group customers by shared criteria for targeted support.\n\n### Creating a segment\n\n1. Go to **Segments** in the sidebar.\n2. Click **New Segment**.\n3. Enter a name and description.\n4. Add filter rules (e.g., LTV > $500, Order count > 3).\n5. Save. The customer count is calculated automatically.\n\n### Available filters\n\n- **Lifetime value** — greater than, less than a dollar amount\n- **Order count** — number of orders placed\n- **Account age** — days since first seen\n- **Total spent** — cumulative spending\n- **Open tickets** — number of currently open tickets\n\n### Use cases\n\n- **VIP customers** — LTV > $1,000 → Route to senior agents\n- **At-risk** — 3+ open tickets → Prioritize\n- **New customers** — Account age < 30 days → Send welcome macro\n\n### Segments in rules\n\nYou can reference segment criteria in automation rules to create segment-specific workflows.` },
  { slug: "sla-policies", title: "SLA policies", category: "Advanced Features", content: `## SLA policies\n\nService Level Agreements define response and resolution time targets.\n\n### Creating an SLA policy\n\n1. Go to **Settings → SLA**.\n2. Click **New Policy**.\n3. Set a name (e.g., "Urgent SLA").\n4. Choose a priority level (Low, Medium, High, Urgent).\n5. Set **First response time** (e.g., 30 minutes).\n6. Set **Resolution time** (e.g., 4 hours).\n7. Choose whether to count **business hours only**.\n8. Save.\n\n### How SLA is enforced\n\n- The SLA checker runs every 60 seconds.\n- If a ticket breaches its first-response or resolution target, it is flagged.\n- Agents see SLA status on tickets in the inbox.\n- Analytics show SLA compliance rates.\n\n### Business hours\n\nIf "Business hours only" is enabled, the SLA timer pauses outside your configured business hours (set in Settings → General).` },
  { slug: "webhook-endpoints", title: "Webhook endpoints", category: "Advanced Features", content: `## Webhook endpoints\n\nWebhooks push real-time events to your external systems.\n\n### Setting up a webhook\n\n1. Go to **Settings → Webhooks**.\n2. Click **Add Endpoint**.\n3. Enter your URL (must be HTTPS).\n4. Select which events to receive:\n   - ticket.created\n   - ticket.resolved\n   - ticket.escalated\n   - ticket.assigned\n   - ai.replied\n5. Save. A signing secret is generated automatically.\n\n### Verifying signatures\n\nEach webhook delivery includes an \`X-Replyma-Signature\` header. Verify it using HMAC-SHA256 with your signing secret to ensure the request is genuine.\n\n### Retry policy\n\nFailed deliveries are retried 3 times with exponential backoff (2s, 4s, 8s).\n\n### Testing\n\nClick **Test** on any endpoint to send a sample payload. Check your server logs to confirm receipt.` },
  { slug: "email-templates", title: "Email templates", category: "Advanced Features", content: `## Email templates\n\nCustomize the emails Replyma sends on your behalf.\n\n### Managing templates\n\n1. Go to **Settings → Templates**.\n2. Browse system templates or create custom ones.\n3. Click **Edit** to modify a template.\n4. Use variables like \`{{customer_name}}\`, \`{{ticket_id}}\`, \`{{agent_name}}\`.\n5. Save.\n\n### Template types\n\n- **System templates** — built-in templates for CSAT surveys, password resets, team invites. You can customize the text but not delete them.\n- **Custom templates** — your own templates for specific scenarios.\n\n### Variables\n\nTemplates support these variables:\n- \`{{customer_name}}\` — customer's display name\n- \`{{ticket_id}}\` — ticket identifier\n- \`{{order_id}}\` — associated order number\n- \`{{agent_name}}\` — name of the assigned agent\n\nVariables are replaced with real data when the email is sent.` },
  { slug: "notification-preferences", title: "Notification preferences", category: "Advanced Features", content: `## Notification preferences\n\nControl which notifications you receive and how.\n\n### Configuring\n\n1. Go to **Settings → Notifications**.\n2. Toggle each notification type on or off.\n3. Save.\n\n### Notification types\n\n- **Email notifications** — receive notifications via email\n- **Push notifications** — browser push notifications\n- **New tickets** — when a new ticket is created in your workspace\n- **Ticket assigned** — when a ticket is assigned to you\n- **Escalations** — when a ticket is escalated to a human\n- **CSAT responses** — when a customer submits satisfaction feedback\n- **Weekly digest** — summary of your support metrics every Monday\n\n### Real-time dashboard notifications\n\nThe bell icon in the sidebar shows recent activity. Notifications appear in real-time via Pusher — no refresh needed.\n\n### Tips\n\n- Enable "Ticket assigned" to never miss a ticket routed to you.\n- Enable "Escalations" if you are a senior agent who handles complex issues.\n- The weekly digest is useful for managers who want a high-level overview.` },
  { slug: "customer-portal", title: "Customer self-service portal", category: "Advanced Features", content: `## Customer self-service portal\n\nThe portal lets your customers check tickets and browse help articles without contacting support.\n\n### How it works\n\nEach workspace has a portal at \`replyma.com/{your-workspace-slug}\`.\n\n### Customer authentication\n\nCustomers verify their identity with an email OTP:\n1. Customer enters their email address.\n2. A 6-digit code is sent (valid for 10 minutes).\n3. After verification, they can see their tickets and create new ones.\n\n### Portal features\n\n- **Help Center** — browse published knowledge base articles by category, search, and view full content.\n- **My Tickets** — view all tickets associated with their email, see full message threads, and reply.\n- **Create Ticket** — submit a new support request with subject and description.\n- **"Was this helpful?"** — feedback on help articles.\n\n### Branding\n\nThe portal shows your workspace name and logo. The header and footer link back to your portal landing page.\n\n### Access\n\nShare the portal URL with your customers. Add it to your website footer, order confirmation emails, or FAQ page.` },
  { slug: "audit-log", title: "Audit log", category: "Advanced Features", content: `## Audit log\n\nThe audit log tracks every significant action in your workspace.\n\n### Viewing the log\n\n1. Go to **Audit Log** in the sidebar.\n2. Browse entries in reverse chronological order.\n3. Filter by entity type (Ticket, User, Channel, etc.).\n4. Use infinite scroll to load more entries.\n\n### What is logged\n\n- Ticket created, updated, merged, deleted\n- User login, logout, invited, removed, role changed\n- Channel configured, disconnected\n- Settings updated\n- API key created, revoked\n- Webhook endpoints created, updated\n- Help articles published\n- Shopify refunds and cancellations\n- AI settings changes\n\n### Entry details\n\nEach entry shows:\n- **Action** — what happened (e.g., "ticket.created")\n- **Entity** — what was affected (e.g., Ticket, User)\n- **User** — who performed the action\n- **Timestamp** — when it happened\n- **Metadata** — additional details (e.g., which fields changed)\n\n### Retention\n\nAudit logs are kept indefinitely. They cannot be deleted by workspace users.` },
]

// ─── Integrations ────────────────────────────────

const ig: Article[] = [
  { slug: "klaviyo-integration", title: "Klaviyo integration", category: "Integrations", content: `## Klaviyo integration\n\nSync customer data and view Klaviyo events from the ticket sidebar.\n\n### Connecting\n\n1. Go to **Settings → Integrations**.\n2. Find Klaviyo and click **Connect**.\n3. Enter your Klaviyo Private API Key.\n4. Replyma verifies the key with Klaviyo's API.\n5. Once verified, the integration is active.\n\n### What it does\n\n- **Customer events** — view recent Klaviyo events (email opens, clicks, purchases) in the customer sidebar when viewing a ticket.\n- **AI context** — the AI can reference Klaviyo engagement data when crafting replies.\n\n### Finding your API key\n\nIn Klaviyo: Go to **Settings → API Keys → Create Private API Key**. Select "Read Only" scope.\n\n### Disconnecting\n\nGo to **Settings → Integrations**, find Klaviyo, and click **Disconnect**.` },
  { slug: "recharge-integration", title: "Recharge integration", category: "Integrations", content: `## Recharge integration\n\nView and manage subscription data from the ticket sidebar.\n\n### Connecting\n\n1. Go to **Settings → Integrations**.\n2. Find Recharge and click **Connect**.\n3. Enter your Recharge API Access Token.\n4. Save.\n\n### What it does\n\n- View active subscriptions for each customer in the ticket sidebar.\n- See next charge dates, subscription products, and order frequency.\n- Agents can quickly understand subscription context when handling support requests.\n\n### Finding your API token\n\nIn Recharge: Go to **Apps → API tokens → Create token**. Select read permissions for customers and subscriptions.` },
  { slug: "loop-returns-integration", title: "Loop Returns integration", category: "Integrations", content: `## Loop Returns integration\n\nProcess returns directly from the Replyma inbox via Loop Returns.\n\n### Connecting\n\n1. Go to **Settings → Integrations**.\n2. Find Loop Returns and click **Connect**.\n3. Enter your Loop Returns API Key.\n4. Save.\n\n### What it does\n\n- When a customer requests a return, agents can initiate it via Loop Returns without leaving Replyma.\n- Return requests from the customer portal automatically check if Loop Returns is connected.\n- If connected, returns are processed through Loop's system. If not, a standard support ticket is created.\n\n### Customer portal returns\n\nCustomers can request returns from the self-service portal. If Loop Returns is connected, the return is initiated automatically.` },
  { slug: "yotpo-integration", title: "Yotpo integration", category: "Integrations", content: `## Yotpo integration\n\nAccess product reviews and loyalty data in the support sidebar.\n\n### Connecting\n\n1. Go to **Settings → Integrations**.\n2. Find Yotpo and click **Connect**.\n3. Enter your Yotpo App Key.\n4. Save.\n\n### What it does\n\n- View product reviews for items in a customer's order.\n- Helps agents understand product quality context when handling complaints.\n- The AI can reference review data when answering product questions.` },
]

export const categories: Category[] = [
  { iconKey: "Bot", title: "Getting Started", articles: gs },
  { iconKey: "MessageSquare", title: "Channels & Inbox", articles: ch },
  { iconKey: "ShoppingCart", title: "Shopify & WooCommerce", articles: sh },
  { iconKey: "Zap", title: "Automation & Rules", articles: au },
  { iconKey: "BarChart3", title: "Analytics & Reports", articles: an },
  { iconKey: "BookOpen", title: "Knowledge Base & AI", articles: kb },
  { iconKey: "CreditCard", title: "Billing & Account", articles: ba },
  { iconKey: "Users", title: "Team & Permissions", articles: tm },
  { iconKey: "Settings", title: "Advanced Features", articles: af },
  { iconKey: "Puzzle", title: "Integrations", articles: ig },
]

export const allArticles: Article[] = categories.flatMap(c => c.articles)

export function getArticleBySlug(slug: string): Article | undefined {
  return allArticles.find(a => a.slug === slug)
}

export function getCategoryByTitle(title: string): Category | undefined {
  return categories.find(c => c.title === title)
}
